version: '3'
services:
  java:
    image: rahamshaik/nitjava:v1
    ports:
      - "8000:80"
    volumes:
      - "javavolume"
    deploy:
      replicas: 3

  devops:
    image: rahamshaik/nitdevops:v1
    ports:
      - "8001:80"
    volumes:
      - "devopsvolume"
    deploy:
      replicas: 3

  datascience:
    image: rahamshaik/nitdatascience:v1
    ports:
      - "8002:80"
    volumes:
      - "datasciencevolume"
    deploy:
      replicas: 3
